name: Benchmark
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'

jobs:
  benchmark:
    name: Run Rust benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cache/pip
            target
          key: ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: pip install -r bench-requirements.txt
      - name: Run benchmark
        run: cargo +nightly bench --no-default-features --features tests --bench comparison | tee output.txt
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          skip-fetch-gh-pages: true
          gh-pages-branch: main
          benchmark-data-dir-path: docs/bench
          output-file-path: output.txt
          auto-push: false
      - name: Push benchmark result
        # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
        run: git push 'https://Anexen:${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/Anexen/pyxirr.git' main:main
