name: Benchmark
on:
  push:
    tags: ['v*']
    paths-ignore:
      - 'docs/**'
  workflow_dispatch:
    inputs:
      build:
        description: 'Build'
        required: true
        default: true

jobs:
  benchmark:
    name: Run Rust benchmark
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event.inputs.build }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cache/pip
            target
          key: ubuntu-latest-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: pip install -r bench-requirements.txt
      - name: Run benchmark
        run: cargo +nightly bench --no-default-features --features tests --bench comparison | tee output.txt
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Rust Benchmark
          tool: 'cargo'
          gh-pages-branch: main
          gh-repository: github/Anexen/pyxirr
          benchmark-data-dir-path: docs/bench
          output-file-path: output.txt
          auto-push: true
          github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
